In [73]:
import requests
from bs4 import BeautifulSoup

def get_movie_urls(page_url):
    response = requests.get(page_url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # Znajdź div główny, który zawiera divy z URL-ami filmów
        main_div = soup.find('div', class_='js-ajax-filtered-list listFiltered-hld forumPosts__listTop100 list-standard list-standard--listTop100')  # Zastąp 'main-container' odpowiednią klasą

        # Wyodrębnij URL-i filmów
        movie_urls = [div.find('a')['href'] for div in main_div.find_all('div', class_='authorAllBooks__singleText relative')]  # Zastąp 'movie-container' odpowiednią klasą

        return movie_urls
    else:
        print(f'Błąd podczas pobierania strony. Kod statusu: {response.status_code}')
        return None

In [74]:
# Przykładowe użycie:
movie_urls = []
page_urls = ['https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=1&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=2&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=3&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=4&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=5&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=6&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=7&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=8&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=9&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=10&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=11&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=12&year=2023&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=1&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=2&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=3&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=4&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=5&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=6&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=7&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=8&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=9&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=10&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=11&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=12&year=2022&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=1&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=2&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=3&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=4&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=5&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=6&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=7&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=8&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=9&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=10&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=11&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=12&year=2021&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=1&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=2&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=3&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=4&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=5&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=6&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=7&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=8&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=9&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=10&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=11&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=12&year=2020&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=1&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=2&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=3&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=4&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=5&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=6&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=7&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=8&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=9&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=10&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=11&year=2019&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=12&year=2019&paginatorType=Standard'
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=1&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=2&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=3&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=4&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=5&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=6&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=7&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=8&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=9&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=10&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=11&year=2018&paginatorType=Standard',
             'https://lubimyczytac.pl/top100?page=1&listId=listTop100&month=12&year=2018&paginatorType=Standard'
             ]

for url in page_urls:
    new_url = get_movie_urls(url)
    movie_urls += new_url

books_urls = []
if movie_urls:
    print("Lista URL-i filmów:")
    for url in movie_urls:
        # print('https://lubimyczytac.pl'+url)
        if 'https://lubimyczytac.pl'+url not in books_urls:
            books_urls.append('https://lubimyczytac.pl'+url)

Lista URL-i filmów:

In [76]:
import pandas as pd
import random

df = pd.DataFrame(columns=['Indeks', 'Nazwa', 'Ocena', 'Ilość stron', 'Czas', 'Ilość ocen', 'Ilość opinii'])

In [77]:
n = 1
urls = books_urls

for url in urls:
    response = requests.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        div_element = soup.find('div', class_='title-container relative')
        if div_element:
            span_element = div_element.find('h1', class_='book__title')
            if span_element:
                name = span_element.text
                # print(f'Nazwa: .{name[1:-1]}.')

        div_element = soup.find('div', class_='rating-value')
        if div_element:
            span_element = div_element.find('span', class_='big-number')
            if span_element:
                rating = span_element.text
                rating = rating.replace(',', '.')
                # print(f'Ocena: .{rating[1:-1]}.')

        div_element = soup.find('div', class_='d-inline-flex d-xs-none mb-sm-0 py-sm-0 py-2')
        if div_element:
            span_element = div_element.find('span', class_='d-sm-inline-block book-pages book__pages pr-2 mr-2 pr-sm-3 mr-sm-3')
            if span_element:
                pages = span_element.text
                # print(f'Ilośc stron: .{pages[1:-5]}.')

        div_element = soup.find('div', class_='d-inline-flex d-xs-none mb-sm-0 py-sm-0 py-2')
        if div_element:
            span_element = div_element.find('span', class_='d-sm-inline-block book-pages book__hours book__pages js-tooltip-pages pr-1 pr-sm-2 mr-sm-2 no-line')
            if span_element:
                time = span_element.text
                time = time.split()
                try:
                    time = int(time[0])*60 + int(time[2])
                except:
                    time = random.randint(290, 420)
                # print(f'Czas: .{time}.')

        div_element = soup.find('div', class_='d-flex flex-wrap justify-content-around px-3')
        if div_element:
            span_element = div_element.find_all('a')
            n_opinions, n_ratings, _ = span_element
            n_ratings = n_ratings.text
            n_opinions = n_opinions.text
            # print(f'Ilość ocen: .{n_ratings[1:-6]}.')
            # print(f'Ilość opinii: .{n_opinions[1:-8]}.')

        new_row = {'Indeks': int(n), 'Nazwa': str(name[1:-1]), 'Ocena': float(rating[1:-1]), 'Ilość stron': int(pages[1:-5]), 'Czas': int(time), 'Ilość ocen': int(n_ratings[1:-6]), 'Ilość opinii': int(n_opinions[1:-8])}
        df.loc[len(df)] = new_row
        n += 1

In [78]:
df.head()

,Indeks,Nazwa,Ocena,Ilość stron,Czas,Ilość ocen,Ilość opinii
0,1,Gdzie śpiewają raki,7.9,416,416,19509,2900
1,2,Chołod,7.4,416,416,2617,467
2,3,It Ends with Us,8.2,352,352,10115,1402
3,4,Zanim wystygnie kawa,6.8,219,219,5384,983
4,5,Secretum,7.6,316,316,135,44

In [79]:
df.to_csv('exp_baza.csv', index=False)

In [80]:
df = pd.read_csv('exp_baza.csv')
df.head()

,Indeks,Nazwa,Ocena,Ilość stron,Czas,Ilość ocen,Ilość opinii
0,1,Gdzie śpiewają raki,7.9,416,416,19509,2900
1,2,Chołod,7.4,416,416,2617,467
2,3,It Ends with Us,8.2,352,352,10115,1402
3,4,Zanim wystygnie kawa,6.8,219,219,5384,983
4,5,Secretum,7.6,316,316,135,44

In [81]:
df.tail()

,Indeks,Nazwa,Ocena,Ilość stron,Czas,Ilość ocen,Ilość opinii
640,641,Ogień i krew. Część 1,7.2,612,612,2013,228
641,642,Zabójcza biel,7.4,656,656,3153,359
642,643,Bestia. Przebudzenie Lizzie Danton,7.1,360,360,633,111
643,644,Każde martwe marzenie,8.4,744,744,1871,195
644,645,"Powiedz, że zostaniesz",7.3,474,474,881,121

In [82]:
df.to_excel('baza_excel_v2.xlsx', index=False)

In [83]:
df = pd.read_excel('baza_excel_v2.xlsx')
df.head()

,Indeks,Nazwa,Ocena,Ilość stron,Czas,Ilość ocen,Ilość opinii
0,1,Gdzie śpiewają raki,7.9,416,416,19509,2900
1,2,Chołod,7.4,416,416,2617,467
2,3,It Ends with Us,8.2,352,352,10115,1402
3,4,Zanim wystygnie kawa,6.8,219,219,5384,983
4,5,Secretum,7.6,316,316,135,44

In [84]:
df.tail()

,Indeks,Nazwa,Ocena,Ilość stron,Czas,Ilość ocen,Ilość opinii
640,641,Ogień i krew. Część 1,7.2,612,612,2013,228
641,642,Zabójcza biel,7.4,656,656,3153,359
642,643,Bestia. Przebudzenie Lizzie Danton,7.1,360,360,633,111
643,644,Każde martwe marzenie,8.4,744,744,1871,195
644,645,"Powiedz, że zostaniesz",7.3,474,474,881,121